### ISSUE TITLE
Inconsistent state between signInResult.signInState, isSignedIn, and currentUserState upon sign in

### ISSUE THREAD

**Issue by kirilstrax** [aws-amplify/aws-sdk-ios#1314]
**Describe the bug**
After calling `AWSMobileClient.sharedInstance().signIn`, `signInResult.signInState` is 'signedIn', but `isSignedIn` is 'false' and `currentUserState` is 'signedOut'.

**To Reproduce**
1. Initial state: user logged out and application is restarted
2. AWSMobileClient is initialized:
```
AWSMobileClient.sharedInstance().initialize { ...
```
3. User is presented with custom login UI. User fills in username and password, and clicks Login button, which triggers the following code:
```
AWSMobileClient.sharedInstance().signIn(username: self.username.text!, password: self.password.text!, completionHandler: { (result, error) in
                
                 if let _error = error {
                    print("Sign in failed: \(String(describing: error))")
                    return
                }
                
                if let signInResult = result {
                    switch(signInResult.signInState) {
                    case .signedIn:
                        print("User signed in successfully. Is signed in = \(AWSMobileClient.sharedInstance().isSignedIn); Current State = \(AWSMobileClient.sharedInstance().currentUserState)")
                    case .smsMFA:
                        print("Code was sent via SMS to \(signInResult.codeDetails!.destination!)")
                    case .newPasswordRequired:
                        print("A change of password is needed. Please provide a new password.")
                    default:
                        print("Other signIn state: \(signInResult.signInState)")
                    }
                }
```
4. When I run the above code, the following line is printed:
```
User signed in successfully. Is signed in = false; Current State = signedOut
```
5. If I restart the application (without signing out), and call 
```
print("Is logged in = \(AWSMobileClient.sharedInstance().isSignedIn); Current State = \(AWSMobileClient.sharedInstance().currentUserState)")
``` 
upon initialization, I see
```
Is logged in = true; Current State = signedIn
```
So clearly login was successful, but status of 3 variables is inconsistent.

**Which AWS service(s) are affected?**
AWSMobileClient

**Expected behavior**
Upon login I expect signInResult.signInState, isSignedIn, and currentUserState to be in consistent state.

**Screenshots**
N/A

**Environment(please complete the following information):**
 - SDK Version: 2.9.3
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone 7 or above
 - iOS Version: iOS 11 or above
 - Specific to simulators: no

**Additional context**

**Comment by minbi** [comment]
Hi @kirilstrax ,

We will try to provide better documentation regarding these states.

**Comment by thomers** [comment]
Hi @minbi , could you elaborate please why this is not a bug? Should we not check `currentUserState`?

**Comment by minbi** [comment]
I think I misread this with another post from the same person. You are correct, this seems like a bug.

**Comment by vladspreys** [comment]
Hello Team,

Any update on this, please?

**Comment by thomers** [comment]
Thank you @royjit !

**Comment by palpatim** [comment]
We released this in https://github.com/aws-amplify/aws-sdk-ios/releases/2.11.0

Please let us know if you have any problems with this.

**Comment by amuresia** [comment]
@palpatim I'm sorry to say that this is still happening on 2.11.0. I've updated to the latest SDK via CocoaPods.
```
Installing AWSAPIGateway 2.11.1 (was 2.9.10)
Installing AWSAppSync 2.14.3 (was 2.14.0)
Installing AWSAuthCore 2.11.1 (was 2.9.10)
Installing AWSAuthUI 2.11.1 (was 2.9.10)
Installing AWSCognitoIdentityProvider 2.11.1 (was 2.9.10)
Using AWSCognitoIdentityProviderASF (1.0.1)
Installing AWSCore 2.11.1 (was 2.9.10)
Installing AWSMobileClient 2.11.1 (was 2.9.10)
Installing AWSS3 2.11.1 (was 2.9.10)
Installing AWSUserPoolsSignIn 2.11.1 (was 2.9.10)
Using ReachabilitySwift (4.3.0)
Using SQLite.swift (0.11.6)
```

But the following function:
```
func signIn(completionHandler: @escaping ((SignInState?, Error?) -> Void)) {
        AWSMobileClient.sharedInstance().signIn(username: self.email, password: self.password) { (signInResult, error) in
            if let result = signInResult {
                switch (result.signInState) {
                case .signedIn:
                    print("isSignedIn", AWSMobileClient.sharedInstance().isSignedIn)
                    print("currentUserState",  AWSMobileClient.sharedInstance().currentUserState)
                    
                default:
                    completionHandler(result.signInState, nil)
                }
                if let error = error as? AWSMobileClientError {
                    print("[ERROR] \(error.localizedDescription)")
                    completionHandler(nil, error)
                }
            }
        }
    }
```
prints:
```
isSignedIn false
currentUserState signedOut
```

**Comment by TrekSoft** [comment]
Don't know if I'm missing something but isSignedIn false is consistent with a state of signedOut, correct?

**Comment by kshrikant** [comment]
The `AWSMobileClient.default().isSignedIn` is not giving valid state, as i logged in the `AWSMobileClient.default().isSignedIn` is giving `true` But when i reopen the App the state changes to `false` 

May i know what the wrong with anything with implementation ?
