### ISSUE TITLE
CRASH: startPasswordAuthentication must be used from main thread only.

### ISSUE THREAD

**Issue by elisgjana** [aws-amplify/aws-sdk-ios#2372]
- What service are you using?
AWS Cognito

I am developing an application in Swift using AWS Cognito authentication same as in this sample: 
https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoYourUserPools-Sample/Swift/CognitoYourUserPoolsSample

The authentication used to work correctly but after some months of working properly, it crashed with this error:

**UIViewController.init(coder:) must be used from main thread only**
**Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.**

I am familiar with this kind of error and I usually fix these types of errors by performing everything in the main thread. The problem in this case is the fact that the function that needs to be performed in the main thread is related with startPasswordAuthentication: 

<img width="930" alt="Screenshot 2020-03-19 at 19 26 32" src="https://user-images.githubusercontent.com/45203732/77101459-9ed87780-6a17-11ea-8be7-043423075bc2.png">

Backtrace:
4   Home One                            0x0000000100689fd8 $s8Home_One20SignInViewControllerC5coderACSgSo7NSCoderC_tcfc + 488
5   Home One                            0x000000010068a098 $s8Home_One20SignInViewControllerC5coderACSgSo7NSCoderC_tcfcTo + 60
6   UIKitCore                           0x00000001bf506cf8 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 7126264
7   UIFoundation                        0x00000001bedc524c 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 447052
8   UIFoundation                        0x00000001bedc5480 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 447616
9   UIFoundation                        0x00000001bed6000c 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 32780
10  UIKitCore                           0x00000001bf505fec AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 7122924
11  UIKitCore                           0x00000001bf234d60 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 4169056
12  UIKitCore                           0x00000001bf18f3cc AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 3490764
13  UIKitCore                           0x00000001bf506cf8 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 7126264
14  UIFoundation                        0x00000001bedc524c 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 447052
15  UIFoundation                        0x00000001bed6000c 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 32780
16  UIKitCore                           0x00000001bf50aea4 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 7143076
17  UIFoundation                        0x00000001bedc524c 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 447052
18  UIFoundation                        0x00000001bedc5480 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 447616
19  UIFoundation                        0x00000001bed6000c 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 32780
20  UIKitCore                           0x00000001bf505dd0 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 7122384
21  UIKitCore                           0x00000001bf508a08 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 7133704
22  UIKitCore                           0x00000001bf9db050 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 12189776
23  Home One                            0x00000001008e59e4 $s8Home_One11AppDelegateC27startPasswordAuthenticationSo018AWSCognitoIdentityfG0_pyF + 500
24  Home One                            0x00000001008e6b24 $s8Home_One11AppDelegateC27startPasswordAuthenticationSo018AWSCognitoIdentityfG0_pyFTo + 40
25  AWSCognitoIdentityProvider          0x000000010169ab3c -[AWSCognitoIdentityUser interactiveAuth] + 1312
26  AWSCognitoIdentityProvider          0x00000001016944bc __36-[AWSCognitoIdentityUser getSession]_block_invoke + 224
27  AWSCore                             0x0000000101975b18 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 108
28  AWSCore                             0x000000010191e228 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 164
29  AWSCore                             0x000000010191eaf0 -[AWSExecutor execute:] + 120
30  AWSCore                             0x0000000101975f8c __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke.105 + 52
31  AWSCore                             0x000000010197556c -[AWSTask runContinuations] + 532
32  AWSCore                             0x0000000101975038 -[AWSTask trySetError:] + 256
33  AWSCore                             0x0000000101976f88 -[AWSTaskCompletionSource setError:] + 112
34  AWSCore                             0x00000001019a1318 __61-[AWSURLSessionManager URLSession:task:didCompleteWithError:]_block_invoke + 6908
35  AWSCore                             0x000000010197641c __63-[AWSTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke + 160
36  AWSCore                             0x0000000101975b18 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 108
37  AWSCore                             0x000000010191e228 __30+[AWSExecutor defaultExecutor]_block_i2020-03-19 19:11:58.716140+0100 Home One[57415:17587875] [reports] Main Thread Checker: UI API called on a background thread: -[UIViewController initWithCoder:]
PID: 57415, TID: 17587875, Thread name: (none), Queue name: NSOperationQueue 0x104223020 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   Home One                            0x0000000100689fd8 $s8Home_One20SignInViewControllerC5coderACSgSo7NSCoderC_tcfc + 488
5   Home One                            0x000000010068a098 $s8Home_One20SignInViewControllerC5coderACSgSo7NSCoderC_tcfcTo + 60
6   UIKitCore                           0x00000001bf506cf8 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 7126264
7   UIFoundation                        0x00000001bedc524c 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 447052
8   UIFoundation                        0x00000001bedc5480 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 447616
9   UIFoundation                        0x00000001bed6000c 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 32780
10  UIKitCore                           0x00000001bf505fec AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 7122924
11  UIKitCore                           0x00000001bf234d60 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 4169056
12  UIKitCore                           0x00000001bf18f3cc AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 3490764
13  UIKitCore                           0x00000001bf506cf8 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 7126264
14  UIFoundation                        0x00000001bedc524c 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 447052
15  UIFoundation                        0x00000001bed6000c 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 32780
16  UIKitCore                           0x00000001bf50aea4 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 7143076
17  UIFoundation                        0x00000001bedc524c 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 447052
18  UIFoundation                        0x00000001bedc5480 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 447616
19  UIFoundation                        0x00000001bed6000c 117385E2-1EB1-3E7D-B551-868BCFDC0286 + 32780
20  UIKitCore                           0x00000001bf505dd0 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 7122384
21  UIKitCore                           0x00000001bf508a08 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 7133704
22  UIKitCore                           0x00000001bf9db050 AA897CA9-8D15-3DD7-BB4F-8D90F9A28571 + 12189776
23  Home One                            0x00000001008e59e4 $s8Home_One11AppDelegateC27startPasswordAuthenticationSo018AWSCognitoIdentityfG0_pyF + 500
24  Home One                            0x00000001008e6b24 $s8Home_One11AppDelegateC27startPasswordAuthenticationSo018AWSCognitoIdentityfG0_pyFTo + 40
25  AWSCognitoIdentityProvider          0x000000010169ab3c -[AWSCognitoIdentityUser interactiveAuth] + 1312
26  AWSCognitoIdentityProvider          0x00000001016944bc __36-[AWSCognitoIdentityUser getSession]_block_invoke + 224
27  AWSCore                             0x0000000101975b18 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 108
28  AWSCore                             0x000000010191e228 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 164
29  AWSCore                             0x000000010191eaf0 -[AWSExecutor execute:] + 120
30  AWSCore                             0x0000000101975f8c __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke.105 + 52
31  AWSCore                             0x000000010197556c -[AWSTask runContinuations] + 532
32  AWSCore                             0x0000000101975038 -[AWSTask trySetError:] + 256
33  AWSCore                             0x0000000101976f88 -[AWSTaskCompletionSource setError:] + 112
34  AWSCore                             0x00000001019a1318 __61-[AWSURLSessionManager URLSession:task:didCompleteWithError:]_block_invoke + 6908
35  AWSCore                             0x000000010197641c __63-[AWSTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke + 160
36  AWSCore                             0x0000000101975b18 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 108
37  AWSCore                             0x000000010191e228 __30+[AWSExecutor defaultExecutor]_block_i

I am a junior IOS developer and I am not familiar with Objective C in order to debug this problem. I would really appreciate if you could help me with this situation because my entire application depends on this.

**Comment by kneekey23** [comment]
hi @elisgjana what version of the SDK are you using? I believe this bug was fixed by this PR #2254. We are currently on version 2.13.0, please make sure you are up to date.

**Comment by elisgjana** [comment]
hi @kneekey23 thank you for your fast reply. I just updated to 2.13.0 because I had 2.12.3, but the problem is still the same. It is not fixed yet.

<img width="452" alt="Screenshot 2020-03-19 at 21 28 42" src="https://user-images.githubusercontent.com/45203732/77112059-a18f9880-6a28-11ea-873d-96bf1efa2f5a.png">

<img width="972" alt="Screenshot 2020-03-19 at 21 29 33" src="https://user-images.githubusercontent.com/45203732/77112127-bf5cfd80-6a28-11ea-9025-a3a01371c6a3.png">

**Comment by wooj2** [comment]
Hi @elisgjana,

Looks like the delegate is not being run on the main thread, and it should be since it's interacting with UI elements.  As a workaround, you can check to see if you are running on the main thread, and if not, force the execution onto the main thread.  For example:
```
if !Thread.isMainThread {
    DispatchQueue.main.sync {
        self.navigationController = self.storyboard?.instantiateViewController(withIdentifier: "signinController") as? UINavigationController
    }
} else {
    self.navigationController = self.storyboard?.instantiateViewController(withIdentifier: "signinController") as? UINavigationController
}
```
And similarly, with the signInViewController:
```
if !Thread.isMainThread {
    DispatchQueue.main.sync {
        self.signInViewController = self.navigationController?.viewControllers[0] as? SignInViewController
    }
} else {
    self.signInViewController = self.navigationController?.viewControllers[0] as? SignInViewController
}
```
That being said, seems like you are using some of our lower-level APIs to achieve auth, which we no longer recommend using.  Instead, we recommend adoption of the AWSMobileClient which provides higher level APIs which make it easier to interact with auth.  More information can be found here: https://aws-amplify.github.io/docs/ios/authentication

**Comment by elisgjana** [comment]
Thank you very much it was really helpful. Now it works.
