### ISSUE TITLE
Crash on [AWSIoTMQTTClient webSocketDidOpen:] + 1173

### ISSUE THREAD

**Issue by florentdouine** [aws-amplify/aws-sdk-ios#2770]
**Describe the bug**
Crashlytics shows up some crashs in the AWS SDK. The most common one is a crash on "webSocketDidOpen" function. We didn't identify a clear way to reproduce this crash but it seems to appear more often when returning to app from background.

This crash has already been details in this [issue](https://github.com/aws-amplify/aws-sdk-ios/issues/2313) 

**Stack Trace**
AWSIoTMQTTClient.m – line 1173
-[AWSIoTMQTTClient webSocketDidOpen:]

Crashed: com.apple.root.default-qos
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000a6586a5d0

0  libobjc.A.dylib                0x1b6817c70 objc_retain + 16
1  AWSIoT                         0x107522ab8 -[AWSIoTMQTTClient webSocketDidOpen:] + 1173 (AWSIoTMQTTClient.m:1173)
2  AWSIoT                         0x107586dd8 __39-[AWSSRWebSocket _HTTPHeadersDidFinish]_block_invoke + 476 (AWSSRWebSocket.m:476)
3  libdispatch.dylib              0x1b6786ec4 _dispatch_call_block_and_release + 32
4  libdispatch.dylib              0x1b678833c _dispatch_client_callout + 20
5  libdispatch.dylib              0x1b67976e8 _dispatch_root_queue_drain + 644
6  libdispatch.dylib              0x1b6797d9c _dispatch_worker_thread2 + 116
7  libsystem_pthread.dylib        0x1b67ef6d8 _pthread_wqthread + 216
8  libsystem_pthread.dylib        0x1b67f59c8 start_wqthread + 8

**Environment(please complete the following information):**
 - SDK Version: 2.13.0
 - Dependency Manager: Carthage
 - Swift Version : 5.1
 - Xcode Version: 11.3

**Device Information (please complete the following information):**
 - All kind of devices

**Additional context**
The bug occured only on foreground

**Comment by palpatim** [comment]
@florentdouine As you've noted, we've encountered this issue before but been unable to make any headway on it. In order for us to be able to help, we'll need repro steps, and possibly a code snippet showing your configuration and initialization.

However, in the meantime, please see the very recent update to that issue: https://github.com/aws-amplify/aws-sdk-ios/issues/2313#issuecomment-647947479, where @brendancallahan reports:

> We've done some major refactoring to our app, and noticed that we were starting AWS IoT on the main thread. Initializing the IoT SDK content and interacting with it on a separate dedicated queue seems to have resolved these issues completely.

It may be that you'll be able to resolve your issues by moving your IoT initialization and startup to a dedicated queue (remembering of course to bounce back to the main queue for UI updates as needed).

**Comment by realityworks** [comment]
@palpatim follow up on this issue.

The OP @brandancallahan has only just posted that the issue is still present. And the reason he was not seeing errors was due to the fact that there were issues with Symbolication on his app.

So to confirm, the work around is not going to make any changes.

**Comment by florentdouine** [comment]
Hi,
i'm coming to you after many changes on our app and of course an upgrade of the aws sdk (2.1.6.0)
We are still facing a major crash on the sdk but this time it's linked to the "cleanUpToDecoderStream" function. It seems you added this function in the PR linked to this issue (https://github.com/aws-amplify/aws-sdk-ios/pull/2957)

Here is the stack trace of the crash :

```
Crashed: com.apple.root.default-qos
0  CoreFoundation                 0x18c12c830 CFArrayGetCount + 16
1  CoreFoundation                 0x18c1b2fa8 _CFStreamUnscheduleFromRunLoop + 196
2  AWSIoT                         0x1053b91a4 -[AWSIoTMQTTClient cleanUpToDecoderStream] + 650 (AWSIoTMQTTClient.m:650)
3  AWSIoT                         0x1053bcd78 -[AWSIoTMQTTClient webSocket:didCloseWithCode:reason:wasClean:] + 1234 (AWSIoTMQTTClient.m:1234)
4  AWSIoT                         0x1054233ec __41-[AWSSRWebSocket safeHandleEvent:stream:]_block_invoke_2 + 1610 (AWSSRWebSocket.m:1610)
5  libdispatch.dylib              0x18be16fd0 _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x18be18ac8 _dispatch_client_callout + 20
7  libdispatch.dylib              0x18be29230 _dispatch_root_queue_drain + 656
8  libdispatch.dylib              0x18be298e8 _dispatch_worker_thread2 + 116
9  libsystem_pthread.dylib        0x1d37748cc _pthread_wqthread + 216
10 libsystem_pthread.dylib        0x1d377b77c start_wqthread + 8
```

For information, this crash occurs on 63% in background since we are disconnecting the iot connection each time the appDelegate call `didEnterBackground`

Thanks for you help and please contact me if you want more informations.

**Comment by florentdouine** [comment]
Hi ! Do you have any updates on this issue ? It's now the major crash on our app !

**Comment by wooj2** [comment]
Hi @florentdouine ,

1.  Are you still seeing the crash with regards to `webSocketDidOpen:` or did that crash go away with the recent updates we've made in the SDK?

2.  Sorry to hear you are encountering a crash on `cleanUpToDecoderStream`.  I've tried very hard to reproduce this issue:  I tried to put my device in a poor network condition scenario, connect via websocket, and then attempt to call `iotDataManager.disconnect()` in the app delegate's `didEnterBackground`.  I also tried to introduce sleep/waits to force crashing conditions based on a couple theories, but was unable to cause any crashes.

I re-looked at the recent PR (#2957) we made, and it seems that we switched the order of closing the `NSOutputStream` and removing it from the runloop.  We made this changed based on the source code from this sample [project here](https://developer.apple.com/library/archive/samplecode/SimpleURLConnections/Introduction/Intro.html#//apple_ref/doc/uid/DTS40009245), but in reading the [documentation here](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Streams/Articles/WritingOutputStreams.html), it seems to indicate very clearly to "first close the stream object, remove it from the run loop, and finally release it". Looking at the stack trace, it's possible that we introduced a bug, but being unable to reliably test this scenario makes it difficult to prove that this will serve as a workaround for the crash you are seeing.

In trying to isolate this issue:
A.  Are you able to patch the following PR into your workspace and test? (#3208)
B.  Are you able to revert PR (#2957) and test to see if this issue goes away?

**Comment by palpatim** [comment]
We've merged https://github.com/aws-amplify/aws-sdk-ios/pull/3208 as an optimistic fix for this issue and it will go out on our next release.

**Comment by palpatim** [comment]
We released this on https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.19.0.

In the continuing spirit of optimism :) I'm optimistically closing this issue. If you continue to see issues, please reopen this issue with any additional detail you're able to provide. Please only reopen this issue if you continue to encounter a crash in `cleanUpToDecoderStream`, so we can properly track issues. If you are encountering other problems, please open a new issue with details so we can properly investigate and troubleshoot it.

**Comment by florentdouine** [comment]
Thank you very much for your help. We are going to release a new version of our app very soon with the 2.19.0 AWS SDK version. We will keep you you in touch if the issue is still present !

**Comment by florentdouine** [comment]
Hello !
Unfortunately, the crash is still present in the 2.19.0 sdk... :( 
The stacktrace is still :
```
Crashed: com.apple.root.default-qos
0  CoreFoundation                 0x1aea5bb38 CFArrayGetCount + 16
1  CoreFoundation                 0x1aeae0df0 _CFStreamClose + 264
2  AWSIoT                         0x105187590 -[AWSIoTMQTTClient cleanUpToDecoderStream] + 650 (AWSIoTMQTTClient.m:650)
3  AWSIoT                         0x10518ad28 -[AWSIoTMQTTClient webSocket:didFailWithError:] + 1196 (AWSIoTMQTTClient.m:1196)
4  AWSIoT                         0x1051f5748 __33-[AWSSRWebSocket _failWithError:]_block_invoke_2 + 774 (AWSSRWebSocket.m:774)
5  libdispatch.dylib              0x1ae73f24c _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x1ae740db0 _dispatch_client_callout + 20
7  libdispatch.dylib              0x1ae751a68 _dispatch_root_queue_drain + 656
8  libdispatch.dylib              0x1ae752120 _dispatch_worker_thread2 + 116
9  libsystem_pthread.dylib        0x1f7f647c8 _pthread_wqthread + 216
10 libsystem_pthread.dylib        0x1f7f6b75c start_wqthread + 8
```
We will update this issue on any new informations we will get, but could you investiguate again the code to see if another issue could still be present ?

**Comment by florentdouine** [comment]
@palpatim Could you reopen the issue please ?

**Comment by wooj2** [comment]
@florentdouine -
Can you please open a new issue?
Reason being is because:
1.  This issue was initially opened with an issue stemming from `_HTTPHeadersDidFinish`
```
1 AWSIoT 0x107522ab8 -[AWSIoTMQTTClient webSocketDidOpen:] + 1173 (AWSIoTMQTTClient.m:1173)
2 AWSIoT 0x107586dd8 __39-[AWSSRWebSocket _HTTPHeadersDidFinish]_block_invoke + 476 (AWSSRWebSocket.m:476)
```

2.  The thread changed topics to a crash which stemmed from `AWSSRWebSocket` `safeHandleEvent:stream:`
```
2  AWSIoT                         0x1053b91a4 -[AWSIoTMQTTClient cleanUpToDecoderStream] + 650 (AWSIoTMQTTClient.m:650)
3  AWSIoT                         0x1053bcd78 -[AWSIoTMQTTClient webSocket:didCloseWithCode:reason:wasClean:] + 1234 (AWSIoTMQTTClient.m:1234)
4  AWSIoT                         0x1054233ec __41-[AWSSRWebSocket safeHandleEvent:stream:]_block_invoke_2 + 1610 (AWSSRWebSocket.m:1610)
```

3.  The latest crash you are seeing seems to stem from 
```
2  AWSIoT                         0x105187590 -[AWSIoTMQTTClient cleanUpToDecoderStream] + 650 (AWSIoTMQTTClient.m:650)
3  AWSIoT                         0x10518ad28 -[AWSIoTMQTTClient webSocket:didFailWithError:] + 1196 (AWSIoTMQTTClient.m:1196)
4  AWSIoT                         0x1051f5748 __33-[AWSSRWebSocket _failWithError:]_block_invoke_2 + 774 (AWSSRWebSocket.m:774)
```
Admittedly these might be three different issues, or perhaps a single problem which is manifesting it self in 3 different ways.  

In any case, could you please open a new issue with repro steps, version numbers, etc?  We have tried very hard to reproduce these crashes, but have not had much success.  Any additional information that might be custom to your application in helping us reliably reproduce these crashes will allow us to make forward progress on resolving this issue.

Thanks!
