### ISSUE TITLE
Canceling signOut() in hosted UI alert pop-up leaves inconsistent user state

### ISSUE THREAD

**Issue by doc-rj-celltrak** [aws-amplify/aws-sdk-ios#2886]
**Describe the bug**
We are using hosted UI sign in and a SAML identity provider with Idp sign out flow enabled. When signing out, the user gets the iOS alert popup shown in the image below. If they click on "Cancel" in this popup, the user state is left in an inconsistent state. After this, calling currentUserState() returns UserState.SIGNED_IN as expected. However, calling getUserAttributes() returns error "User is not signed in, please sign in to use this API."

![popup_for_sign_out](https://user-images.githubusercontent.com/55109813/88699326-d1346880-d0cc-11ea-86fe-e3351367a7f5.png)

**To Reproduce**
1. Sign in via showSignIn().
2. Sign out via signOut() and in the popup that says "<app name> wants to use 'amazoncognito.com' to Sign In", click the "Cancel" button.
3. Try calling AwsMobileClient.default().currentUserState().
4. Try calling AwsMobileClient.default().getUserAttributes().
5. Try calling AwsMobileClient.default().getTokens().

**Observed Behavior**
There is inconsistent user state after step 2.
In step 3, currentUserState() returns UserState.SIGNED_IN (as expected).
In step 4, getUserAttributes() returns error "User is not signed in, please sign in to use this API."
In step 5, getTokens() shows the alert popup to sign in.

**Expected Behavior**
The user should still be signed in after step 2, and the user state should be consistent.
In step 4, getUserAttributes() should return the user attributes for the user that is signed in.
In step 5, getTokens() should return the tokens for the signed in session, and should not show the alert popup.

**Stack Trace**
N/A

**Code Snippet**
Using native iOS SDK through Flutter, but here is some pseudocode:
AwsMobileClient.default().showSign()
...
AwsMobileClient.default().signOut()  // hit "Cancel" in the alert popup
AwsMobileClient.default().currentUserState()
AwsMobileClient.default().getUserAttributes()
AwsMobileClient.default().getTokens()

**Unique Configuration**
iOS hardware and simulator

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSMobileClient
Cognito

**Screenshots**

![popup_for_sign_out](https://user-images.githubusercontent.com/55109813/88701010-135ea980-d0cf-11ea-99ef-c113e038fe04.png)

**Environment(please complete the following information):**
 - SDK Version: 2.13.6
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2
 - Xcode Version: 11.4.1

**Device Information (please complete the following information):**
 - Device: iPhone SE (2nd gen) simulator, iPhone 8 hardware
 - iOS Version: iOS 13.4.1 on simulator, iOS 12.4.1 on hardware
 - Specific to simulators: No

**Comment by bumbleparrot** [comment]
Is calling Amplify.Auth.signOut(options: options) supposed to pop up a prompt to open the Hosted UI just to sign out?

Doesn't that feel weird to the user?

**Comment by doc-rj-celltrak** [comment]
@bumbleparrot Yes, I think it will feel weird to the user (we haven't shipped this yet). I'm guessing the pop-up is necessary because the web tab/view is used for both sign in and sign out. I don't know if there's  a great alternative to avoid the pop-up. Issue #2715 proposes one potential alternative as a feature request.

Also, note that currently the pop-up wrongly says "...to Sign In" even when you are signing out, which seems like a bug in the SDK.

**Comment by bumbleparrot** [comment]
@doc-rj-celltrak , I've been exploring just calling the logout URL with the query string parameters.

The issue seems to be that there needs to be some cognito cookie data sent in the request, which isn't available :(

Any thoughts on this work around? Do you know how the cookie data is generated? (I saw it when monitoring via Charles).

[Example issue with workout I posted in Stack overflow](https://stackoverflow.com/questions/63224049/swift-url-with-custom-scheme-in-query-string-fails-redirect-uri)

**Comment by doc-rj-celltrak** [comment]
@bumbleparrot Personally I don't want to bypass the SDK, but I definitely understand why you want a workaround. I agree that ideally there would not be a pop-up for signing out, and it will feel weird for users.  I left a comment on your issue in stack overflow. However, sorry I don't know how the cookie data is generated.

**Comment by Tirthak-Tatva** [comment]
Is there any way to completely bypass this popup ?

**Comment by royjit** [comment]
This has been fixed in the PR #3190 and will be available in the next release.

**Comment by palpatim** [comment]
We released this on https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.18.1

**Comment by kingsofteng** [comment]
This is still happening with 
Amplify 1.5.2
AWSAuthCore 2.21.1
...

@palpatim Can you check and reopen this issue?

**Comment by Newsid** [comment]
I confirm, this is still an issue in 2.24.0.
is seems that the SDK had a regression about that. Is it planned to be fixed again?

**Comment by sainiketan47** [comment]
For iOS you can use Prefer private session during signIn it will not show any alert on signing and signout

Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!, options: .preferPrivateSession()) { ... }

**Comment by MuhammadSalmanSiddiqui** [comment]
Tackle this issue using Javascript, I just added a condition of checking logout word in a path generated on pressing signOut button. That's it.

`async function urlOpener(url, redirectUrl) {
  if (await InAppBrowser.isAvailable()) {
    if (!url.includes("logout")) {
      const { type, url: newUrl } = await InAppBrowser.openAuth(
        url,
        redirectUrl,
        {
          modalEnabled: false,
          showTitle: false,
          enableUrlBarHiding: false,
          enableDefaultShare: false,
          ephemeralWebSession: false,
        }
      );
      if (type === "success") {
        Linking.openURL(newUrl);
      }
    }
  }
}`

**Comment by MrJorgeXavier** [comment]
> For iOS you can use Prefer private session during signIn it will not show any alert on signing and signout
> 
> Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!, options: .preferPrivateSession()) { ... }

This isn't a good option because the user will have to enter their credentials for social login again, which greatly impacts the login flow. Normally, the user use social login because he doesn't want to input his credentials to create an account.

**Comment by prateekbh** [comment]
@MuhammadSalmanSiddiqui InAppBrowser wont work as InAppBrowser and ASWebAuthenticationSession don't share cookies
