### ISSUE TITLE
The app references non-public selectors > AWSAuthCore: reloadSession

### ISSUE THREAD

**Issue by kkh2** [aws-amplify/aws-sdk-ios#4314]
Upgraded to Xcode 14 and started getting this validation error when submitting to the App Store:

"The app references non-public selectors in Payload/<name of app>.app/Frameworks/AWSAuthCore.framework/AWSAuthCore: reloadSession"

Is this a known issue to the AWS team or perhaps a bug Apple needs to fix?

**Comment by thisisabhash** [comment]
Hello,
We are aware of this issue and currently looking into it. We'd encourage to post this on Apple Developer forums as well while we investigate this. In case this is a blocker for you, please let us know.
Similar thread : https://developer.apple.com/forums/thread/713574

**Comment by Tibimac** [comment]
Same issue (with a different selector) on my side since I updated to Xcode 14 : `The app references non-public selectors in Payload/app_name.app/app_name: authenticationDidCompleteWithError:`

**Comment by Nomad-Go** [comment]
In general I would say I wish I did not upgrade to Xcode 14 right away.

**Comment by phantumcode** [comment]
Issue not yet resolved with Apple's validation with latest testing.

**Comment by vishwakneelamegam** [comment]
The app references non-public selectors in Payload/sailors-app-v1.app/Frameworks/AWSAuthCore.framework/AWSAuthCore: reloadSession.  I got this issue in Xcode 14.0.1

**Comment by yaroslav13** [comment]
I also have this issue and for me, this build doesn't display on Testflight.

**Comment by thobiassilva** [comment]
Same problem

**Comment by KyleXie** [comment]
I got 2 warnings after upgraded to Xcode 14:

1. The app references non-public selectors in Payload/xxxx.app/Frameworks/AWSAuthCore.framework/AWSAuthCore: reloadSession
2. The app references non-public selectors in Payload/xxx.app/xxxx: applicationWillEnterForeground

<img width="661" alt="image" src="https://user-images.githubusercontent.com/2870241/194989838-67abdfa8-1418-4acb-83a2-68681501dc16.png">

**Comment by maziar** [comment]
For me I add in info.plist some Privacy:

NSLocationWhenInUseUsageDescription
NSPhotoLibraryUsageDescription
NSContactsUsageDescription
NSCameraUsageDescription

**Comment by Ali1067** [comment]
don't worry these are warning only. but AWSCore have not released anything official yet. i got this warning  after updating to xcode 14. 

my app is published to test-flight and my testers are able to download and test.

**Comment by afern247** [comment]
> don't worry these are warning only. but AWSCore have not released anything official yet. i got this warning after updating to xcode 14.
> 
> my app is published to test-flight and my testers are able to download and test.

warnings are something to be worries, even if it's for a misspelling typo and should be fix. So we worried and should be fixed.

**Comment by phantumcode** [comment]
This is an issue with Apple's code validation.  As of 10/31/2022, this is still an issue with Xcode 14.1 RC2.

This validation issue is not specific to AWS iOS SDK.  See references to the same issue in other code bases: 
* https://issuetracker.google.com/issues/246667837
* https://developer.apple.com/forums/thread/714736
* https://developer.apple.com/forums/thread/713574
* https://github.com/facebook/react-native/issues/34716

**Note: This issue does not block or prevent TestFlight submissions or App approvals.**

We are deferring and waiting for Apple to fix this issue in their code validation.  Fixing this issue in AWS iOS SDK as a workaround would require a signature rename and introduce a breaking change.    If this becomes a block issue in the future, there's already the fix ready in [PR #4366](https://github.com/aws-amplify/aws-sdk-ios/pull/4366)

**Comment by vish7** [comment]
I faced a similar warning message when trying to upload my app to TestFlight using Xcode 14.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/6234726/206986494-96d71e75-cf2a-4ea2-ae02-80dc60ffc29a.png)

**Comment by ranvirm** [comment]
Still experiencing this issue - using Xcode 14

![Screenshot 2023-01-14 at 02 12 51](https://user-images.githubusercontent.com/30086382/212440227-1f7b1527-82cd-4ba3-8b72-2332810521cb.png)

**Comment by engasix** [comment]
Ok, I found a solution I used [Transporter](https://apps.apple.com/us/app/transporter/id1450874784?mt=12) utility to upload binary, I didn't find any warning in logs.

**Comment by afern247** [comment]
> Ok, I found a solution I used [Transporter](https://apps.apple.com/us/app/transporter/id1450874784?mt=12) utility to upload binary, I didn't find any warning in logs.

That's a workaround, not a solution.

**Comment by yanbai100624** [comment]
Currently, I cannot upload to TestFlight with this warning! Xcode 14.2. Any solutions??

**Comment by phantumcode** [comment]
@yanbai100624 I just uploaded a new a test app to AppStoreConnect without any issues using Xcode 14.2.

Previously, I was observing app uploads would succeed but with a warning message, it did not block any upload.  With 14.2 I can successfully upload with no warning.

Can you clarify why or what is blocking your app upload? What are the error logs or screenshot that you can provide?  For my testing, I archived the app and then uploaded using Xcode 14.2; both validation and distribution step succeeded with no warnings.

<img width="752" alt="Screenshot 2023-02-03 at 7 55 15 PM" src="https://user-images.githubusercontent.com/103537251/216740439-24465e44-ebce-4746-8459-345860d6b958.png">

**Comment by mlamaa** [comment]
Issue not yet resolved

**Comment by Sajjad-Zafar** [comment]
issue not resolved yet. using xcode 14.2
<img width="752" alt="Screenshot 2023-03-01 at 1 22 38 PM" src="https://user-images.githubusercontent.com/7095151/222083987-2a62bdb2-8dcf-45e4-864a-93a692bbfbb3.png">
